server:
  port: 9999
  
spring.jpa:
  database: MYSQL
  hibernate.ddl-auto: create-drop
  show-sql: true

spring.datasource:
  platform: mysql
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db1?serverTimezone=UTC&useLegacyDatetimeCode=false
  username: root
  password: rammstein